{
 "title": "Live Dashboard #1",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "eventId",
    "query": "SELECT m1.eventid AS __value, m1.title  AS __text\n    FROM event_master_data AS m1\n    INNER JOIN event_data AS e1 ON m1.eventid = e1.eventid\n    INNER JOIN \n        (SELECT live.eventid, MAX(live.timestamp) as max_ts\n            FROM\n            (SELECT m.eventid, ev.timestamp \n            FROM event_master_data AS m\n                INNER JOIN (SELECT \n                        eventid,\n                        timestamp, \n                        to_timestamp(timestamp) as time, \n                        clocktime\n                    FROM event_data) AS ev\n                ON m.eventid = ev.eventid\n            WHERE $__timeFilter(ev.time)\n            ) AS live\n        GROUP BY live.eventid) AS a1 ON e1.eventid = a1.eventid AND e1.timestamp = a1.max_ts"
   },
   {
    "name": "radarId",
    "query": "SELECT betradarid FROM event_master_data WHERE eventid=$eventId"
   },
   {
    "name": "marketId",
    "query": "SELECT \n    marketid AS __value, \n    (CASE WHEN type='MRES' THEN '  ' WHEN type='HCTG' THEN ' ' ELSE '' END) || type || '_' || handicap || ':  ' || description AS __text\nFROM market_master_data \nWHERE eventid=$eventId\nGROUP BY marketid, type, handicap, description"
   },
   {
    "name": "selectionId",
    "query": "SELECT DISTINCT * FROM (SELECT s.selectionid AS __value, s.description as __text\nFROM selection_master_data AS s\nWHERE s.marketid IN ($marketId)\n) AS source\nORDER BY __value DESC"
   }
  ]
 },
 "panels": [
  {
   "title": "$eventId: $marketId",
   "type": "graph",
   "description": "sadasdsa a sda sdsa",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  s.timestamp AS \"time\",\n  sm.description AS metric,\n  s.currentprice\nFROM selection_data AS s \n  INNER JOIN selection_master_data AS sm ON s.selectionid = sm.selectionid\nWHERE $__unixEpochFilter(s.timestamp)\n  AND s.selectionid IN ($selectionId)\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Radar statistics",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  count(distinct id) as \"match timeline events\"\nFROM match_timeline_events\nWHERE $__unixEpochFilter(timestamp)\nGROUP BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  count(distinct matchid) as \"match situation events\"\nFROM match_situation_events\nWHERE $__unixEpochFilter(timestamp)\nGROUP BY timestamp\n"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  count(distinct matchid) as \"match detail events\"\nFROM match_detail_events\nWHERE $__unixEpochFilter(timestamp)\nGROUP BY timestamp\n"
    }
   ]
  },
  {
   "title": "Live Matches",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT m1.starttime, m1.title, e1.clocktime, e1.homescore || '-' || e1.awayscore as score, e1.suspended, m1.eventid, m1.betradarid\r\n    FROM event_master_data AS m1\r\n    INNER JOIN event_data AS e1 ON m1.eventid = e1.eventid\r\n    INNER JOIN \r\n        (SELECT live.eventid, MAX(live.timestamp) as max_ts\r\n            FROM\r\n            (SELECT m.eventid, ev.timestamp \r\n            FROM event_master_data AS m\r\n                INNER JOIN (SELECT \r\n                        eventid,\r\n                        timestamp, \r\n                        to_timestamp(timestamp) as time, \r\n                        clocktime\r\n                    FROM event_data) AS ev\r\n                ON m.eventid = ev.eventid\r\n            WHERE $__timeFilter(ev.time) \r\n            --WHERE ev.time BETWEEN '2020-02-03T11:41:20.018Z' AND '2020-02-04T11:41:20.018Z'\r\n            ) AS live\r\n        GROUP BY live.eventid) AS a1 ON e1.eventid = a1.eventid AND e1.timestamp = a1.max_ts\r\n    WHERE (e1.clocktime < '90:00' OR e1.suspended = false) AND e1.clocktime > '00:00'\r\n    ORDER BY 1 desc \r\n;"
    }
   ]
  },
  {
   "title": "Score changes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  c.timestamp,\n  clocktime,\n  hometeam || '-' || awayteam as match,\n  home || '-' || away as score,\n  homediff, awaydiff\nFROM event_score_changes AS c\nINNER JOIN event_master_data AS m ON c.eventid = m.eventid\nWHERE\n  $__unixEpochFilter(c.timestamp)\nORDER BY 1 desc\nLIMIT 30"
    }
   ]
  }
 ]
}